[package]
name = "examples-grpc"
version = "0.15.1"
edition = "2021"
publish = false

[dependencies]
init-tracing-opentelemetry = { path = "../../init-tracing-opentelemetry", features = [
  "otlp",
  "tracing_subscriber_ext",
] }
opentelemetry = "0.21"
prost = "0.12"
tokio = { version = "1.0", features = ["full"] }
tonic = { version = "0.10", features = [
  "transport",
  "channel",
  "codegen",
], default-features = false }
tonic-health = "0.10"
tonic-reflection = "0.10"
tonic-tracing-opentelemetry = { path = "../../tonic-tracing-opentelemetry" }
tower = "0.4"
tracing = "0.1"
tracing-opentelemetry-instrumentation-sdk = { path = "../../tracing-opentelemetry-instrumentation-sdk" }

[build-dependencies]
tonic-build = { version = "0.10", default-features = false, features = [
  "transport",
  "prost",
] }


[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
